export const COLOR_TOKENS = {
  canvas: "#F3F0E8",
  surface: "#FBFAF6",
  surfaceMuted: "#EAE6DC",
  surfacePressed: "#DED9CD",
  text: "#18201E",
  textMuted: "#59615E",
  textSubtle: "#747C78",
  border: "#CBC7BC",
  borderStrong: "#979D99",
  accent: "#0B5B52",
  accentHover: "#084940",
  accentSoft: "#DCE9E4",
  onAccent: "#FFFFFF",
  success: "#2F6D52",
  successSoft: "#DFEBE4",
  warning: "#80551B",
  warningSoft: "#F1E6D2",
  critical: "#9A3E34",
  criticalSoft: "#F3DFDC",
} as const

export const COLOR_TOKEN_ENTRIES = [
  ["--color-canvas", COLOR_TOKENS.canvas],
  ["--color-surface", COLOR_TOKENS.surface],
  ["--color-surface-muted", COLOR_TOKENS.surfaceMuted],
  ["--color-surface-pressed", COLOR_TOKENS.surfacePressed],
  ["--color-text", COLOR_TOKENS.text],
  ["--color-text-muted", COLOR_TOKENS.textMuted],
  ["--color-text-subtle", COLOR_TOKENS.textSubtle],
  ["--color-border", COLOR_TOKENS.border],
  ["--color-border-strong", COLOR_TOKENS.borderStrong],
  ["--color-accent", COLOR_TOKENS.accent],
  ["--color-accent-hover", COLOR_TOKENS.accentHover],
  ["--color-accent-soft", COLOR_TOKENS.accentSoft],
  ["--color-on-accent", COLOR_TOKENS.onAccent],
  ["--color-success", COLOR_TOKENS.success],
  ["--color-success-soft", COLOR_TOKENS.successSoft],
  ["--color-warning", COLOR_TOKENS.warning],
  ["--color-warning-soft", COLOR_TOKENS.warningSoft],
  ["--color-critical", COLOR_TOKENS.critical],
  ["--color-critical-soft", COLOR_TOKENS.criticalSoft],
] as const
